### ISSUE TITLE
ConCat will begin allowing users to change their username soon

### ISSUE THREAD

**Issue by ZenIsBestWolf** [GoBLFC/Tracker#41]
Hi there, I'm Zen, a software engineer at ConCat.

I wanted to give you folks a heads up that we intend to allow users to begin changing their usernames soon. Previously, usernames were static and could not be modified.

Please ensure that Tracker does not rely on ``username`` as an immutable key. Instead, you should utilize the user's ID, as that remains immutable.

I have not looked deep into Tracker's code, so no action may be required.

I'm doing my best to be transparent about changes like these that may break applications, in similar spirit of [this](https://github.com/vrcx-team/VRCX/issues/429) issue.

If you have any questions about this change please feel free to reply here or message me on Slack or Telegram.

**Comment by Gawdl3y** [comment]
Thanks for the heads up! Fortunately, Tracker already uses the user's ID from ConCat to correlate with users in its own database (currently stored in the `badge_id` column of the `users` table), so I don't think we need to do anything.

We do also store the username in Tracker's DB so we have a convenient fallback name to call a user that doesn't have any registration details (and thus no badge name). This is updated automatically from what ConCat provides upon them logging in, so username changes should already be accommodated as well.
